### ISSUE TITLE
Vault fails to start

### ISSUE THREAD

**Issue by njsaunders** [kbrebanov/ansible-vault#1]
In order to use mlock you need to be root, but by default the role sets disable_mlock to false but tries to run vault as the vault user/group in the upstart template, which prevents vault from starting (Ubuntu 12.04):

```
Error initializing core: Failed to lock memory: cannot allocate memory

This usually means that the mlock syscall is not available.
Vault uses mlock to prevent memory from being swapped to
disk. This requires root privileges as well as a machine
that supports mlock. Please enable mlock on your system or
disable Vault from using it. To disable Vault from using it,
set the `disable_mlock` configuration option in your configuration
file.
```

Setting vault_user and vault_group to root created system accounts called root, which broke the world.

Suggest that by:
- Default vault is run as root
- Don't try and create user and group if set to root
- If user != root set disable_mlock: true

**Comment by kbrebanov** [comment]
@njsaunders I've added a task to give the Vault executable access to the mlock syscall.
Let me know if this helps.

**Comment by njsaunders** [comment]
Hi Kevin - I can confirm that that's working now - Thanks very much for such a quick fix!
