### ISSUE TITLE
If vault is running, it will not be upgraded

### ISSUE THREAD

**Issue by timbroder** [kbrebanov/ansible-vault#12]
When increasing the vault version on subsequent runs, ansible-vault will download the new version and unzip it correctly but will fail silently when trying to move it to `vault_install_dir`

**Comment by timbroder** [comment]
This might actually have more to do with unzip. Is this expected behavior?

**Comment by kbrebanov** [comment]
It's "expected" behavior the way the role is presently setup.

I had to fix this in the Terraform role https://github.com/kbrebanov/ansible-terraform/commit/ab0266b2ca115400cc7ce3fcbd6afad3f92c4b79

But, I didn't get around to updating this one yet, or any of the other roles for Hashicorp tools.

**Comment by timbroder** [comment]
gotcha. I'll try to get a PR together in the next few days. cool?

**Comment by kbrebanov** [comment]
Sounds good.
