### ISSUE TITLE
Add explicit option to turn on/off HA (for changes to DynamoDB and etcd in 0.6.1 and 0.6.2)

### ISSUE THREAD

**Issue by myth** [kbrebanov/ansible-vault#16]
As per the [0.6.1 and 0.6.2 changelogs](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md), HA is disabled by default for DynamoDB and etcd backends.

For upgrading DynamoDB it is extremely important to enable HA before upgrading if it is in use. The same goes for etcd now with 0.6.2.

Recommending adding a `etcd_ha_enabled` and `dynamodb_ha_enabled` option for their respective backend configs, defaulting to `false`.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
